# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3f33d92bbafc6bffd6465804d072e722f8e40f2108cea75112e1620564745517fc7cb08ddc9223ff982857c88c33c4ee84257e1562322cd0c08e3a06134a7e3
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>

test:
  secret_key_base: 44f3eb26c9d59c1ef29d91252d2afe32f0bc0de707f5eead36b0bdf541879d6d15ffa8114fcbe62b43166aac44b69d9ab1dcc9ac880f14f6a5c6c6b444ddab1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
